version: "3.7"

services:
# configure api
  app:
    build:
      context: .
    ports:
      - "888:3000"
    volumes:
      - ./dist:/app
      - /app/node_modules
    restart: on-failure
    command: >
      node main.js

## configure front
#  web:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    restart: on-failure
#    volumes:
#    - ./build_client:/usr/share/nginx/html
#    - ./nginx.conf:/etc/nginx/conf.d/default.conf

# configure MongoDB
#  db:
#    image: mongo
#    env_file:
#      - .env
#    restart: on-failure
#    ports:
#      - "27018:27017"
#    volumes:
#      - ./mongo-db:/data/db
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
